inhibit_all_warnings!
platform :ios, '7.0'

workspace 'ACYTableViewWrapper.xcworkspace'

def app_pods
    pod 'Masonry'
end

target 'ACYTableViewWrapper' do
    app_pods
end

### HOOK POST 
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_STRICT_OBJC_MSGSEND'] = 'NO'
            config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
    end
end
